name: CI-CD

on:
  push:
    branches:
    - trunk
    - devel
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
    paths-ignore:
    - "COPYRIGHT"
    - "LICENSE-*"
    - "**.md"
    - "**.txt"
  pull_request:
    branches:
    - trunk
    - devel
    paths-ignore:
    - "COPYRIGHT"
    - "LICENSE-*"
    - "**.md"
    - "**.txt"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
    - name: Functional test
      run: poetry run pytest

  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install style deps
      run: pip install flake8 flake8-docstrings flake8-bugbear black isort
    - name: flake8 (check code style)
      run: flake8 escher_maud tests
    - name: black (check code format)
      run: black --check --diff escher_maud tests
    - name: isort (check import sorting)
      run: isort --check-only --diff escher_maud tests
